[package]
name = "yakui-miniquad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniquad = { version = "0.3.13", default-features = false }
yakui = { version = "0.2.0", default_features = false }
